algoritmo "exercicio 1"
var
  contador,numero,numeroMaior : inteiro
inicio

para contador de 1 ate 10 faca
       escreval("Digite o número :")
       leia(numero)
       se (numero > numeroMaior) entao
           numeroMaior <- numero
       fimse
fimpara

escreva("O maior número digitado foi : ")
escreval(numeroMaior)
escreval("-----------FIM-----------")

//mostrar
fimalgoritmo
