Algoritmo "ex11-lista2"

Var

custo,porcentagem,venda: real


Inicio
 escreval("Digite o preço de custo:")
 leia(custo)
 
escreval("..........................................................")

 escreval("Digite a porcentagem de acréscimo ao preço de custo:")
 leia(porcentagem)

venda<- custo+(custo*porcentagem)/100

escreval("..........................................................")

escreval("O preço de venda é:")
escreval(venda)







Fimalgoritmo