Algoritmo "ex13-lista2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/05/2022
Var
numero: inteiro

Inicio
escreval("Digite um número:")
leia(numero)

se (numero>10)entao
   escreval("Esse número é maior que 10")
senao
     escreval("Esse número NÃO é maior que 10")
fimse









Fimalgoritmo