Algoritmo "ex8-lista2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/05/2022
Var
r, dolar, cotacao: real

Inicio
escreval ("escreva o valor em reias")
leia(r)
 escreval("insira a cotação:")
leia(cotacao)
dolar<-r/cotacao
escreval("o valor do dolar é")
escreval(dolar)




Fimalgoritmo