Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/05/2022
Var
deposito: real
rendimento: real
Inicio
escreval("digite o valor depositado na poupançaa:")
leia(deposito)

rendimento<-deposito+(deposito*70)/1000

escreval("o rendimento do mês foi:")
escreval(rendimento)

Fimalgoritmo